/**
 * AI 模型目录 + 查找工具
 *
 * 【优化思路】将 600+ 行的模型数据定义独立为目录模块，
 * 包含模型列表、推荐配置和按条件查找的纯函数。
 */

import type { AIModel, ModelProvider, ModelCategory } from '@/types';

export const AI_MODELS: AIModel[] = [
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 最新旗舰模型（2026），支持多模态输入，适合视频素材分析与解说文案生成。',
    features: ['多模态', '最高智能', '视频理解'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.5-pro',
    name: 'GPT-5.5 Pro',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 最新旗舰 Pro 模型（2026），最高智能水平，适合复杂视频语义分析与高质量解说稿创作。',
    features: ['最高智能', '视频理解', '复杂推理'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性能模型（2026），适合高质量脚本生成与改写。',
    features: ['高性能', '多模态', '编程能力'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性价比模型（2026），响应快、成本低，适合批量剪辑脚本生成与改写。',
    features: ['高性价比', '快速响应', '多模态'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.3-codex',
    name: 'GPT-5.3 Codex',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 代码专用模型（2026），编程能力强，适合代码分析与剪辑逻辑生成。',
    features: ['代码专家', '编程能力', '高智能'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.2',
    name: 'GPT-5.2',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 主力旗舰模型（2026），多模态能力均衡，适合综合视频分析与内容创作。',
    features: ['多模态', '高智能', '均衡全面'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.1',
    name: 'GPT-5.1',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 中高端模型（2026），适合内容分析与高质量文案生成。',
    features: ['多模态', '内容理解', '文案创作'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 基础旗舰模型（2026），支持视频理解，适合复杂视频语义分析。',
    features: ['多模态', '视频理解', '最高智能'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 轻量旗舰（2026），高性价比，适合批量脚本生成与改写。',
    features: ['高性价比', '多模态', '快速'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 旗舰多模态模型（2024-05），支持文本/代码/图像/视频理解，适合视频素材分析与解说文案生成。',
    features: ['多模态', '高智能', '视频理解'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 2.5, output: 10, unit: '$/MTokens' },
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性价比模型（2024-07），响应快、成本低，适合批量剪辑脚本生成与改写。',
    features: ['高性价比', '快速响应', '多模态'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: false,
    pricing: { input: 0.15, output: 0.6, unit: '$/MTokens' },
  },
  {
    id: 'o3',
    name: 'OpenAI o3',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 推理模型（2024-12），擅长复杂推断与规划，适合镜头匹配、时间轴修正等复杂决策。',
    features: ['高级推理', '复杂规划', '可靠判别'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'o3-mini',
    name: 'OpenAI o3-mini',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 轻量推理模型（2025-01），低成本推理，适合批量脚本评分与镜头优先级排序。',
    features: ['低成本推理', '快速', '编程能力'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 1.1, output: 4.4, unit: '$/MTokens' },
  },
  {
    id: 'o3-pro',
    name: 'OpenAI o3 Pro',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 高端推理模型（2026），最强推理能力，适合最复杂的决策与规划任务。',
    features: ['最强推理', '复杂规划', '高端判别'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  // ========== Anthropic ==========
  {
    id: 'claude-sonnet-4.6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2026），长文本组织能力强，适合解说长稿编写与风格润色。',
    features: ['长文处理', '稳定风格', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2026），长文本能力强，适合解说长稿编写与风格润色。',
    features: ['长文处理', '稳定风格', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 主力模型（2026），综合能力均衡，适合各类文本与代码任务。',
    features: ['均衡', '长文处理', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4.7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 最高智能版本（2026），最高智能水平，适合复杂视频语义分析与高质量脚本创作。',
    features: ['最高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4.6',
    name: 'Claude Opus 4.6',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 旗舰模型（2026），适合复杂视频语义分析与高质量脚本创作。',
    features: ['高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4.5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2026），适合复杂视频语义分析与高质量脚本创作。',
    features: ['高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4',
    name: 'Claude Opus 4',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 旗舰基础模型（2026），适合复杂内容分析与高质量脚本创作。',
    features: ['高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-haiku-4.5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    category: ['text', 'code'],
    description: 'Anthropic 轻量高速模型（2026），适合批量分析与低延迟任务。',
    features: ['高速', '低成本', '精准'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2024-06），长文本组织能力强，适合解说长稿编写与风格润色。',
    features: ['长文处理', '稳定风格', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 3, output: 15, unit: '$/MTokens' },
  },
  {
    id: 'claude-3.7-sonnet',
    name: 'Claude 3.7 Sonnet',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 最新 3.7 系列（2025），长上下文与编程能力全面提升，适合复杂代码与长文本任务。',
    features: ['长上下文', '编程能力', '高智能'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  // ========== Google ==========
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google 最新旗舰模型（2026-02），推理能力 2x+ 提升，1M token 上下文，适合超长视频素材理解与多镜头关联分析。',
    features: ['超长上下文', '多模态推理', '视频理解', 'Deep Think模式'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see ai.google.dev/pricing' },
  },
  {
    id: 'gemini-3.1-flash',
    name: 'Gemini 3.1 Flash',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 高性价比模型（2026-03），多模态能力强，适合批量素材分类与标签生成。',
    features: ['高速', '低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 最快最便宜模型（2026-03），适合大批量素材分类与低延迟任务。',
    features: ['高性价比', '快速', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google 旗舰模型（2025），超长上下文，适合长视频素材理解与多镜头关联分析。',
    features: ['超长上下文', '多模态推理', '视频理解'],
    tokenLimit: 2000000,
    contextWindow: 2000000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see ai.google.dev/pricing' },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 高速高性价比模型（2025），多模态能力强，适合批量素材分类与标签生成。',
    features: ['高速', '低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 轻量高性价比模型（2025），适合大批量素材分类与低延迟任务。',
    features: ['高性价比', '快速', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 高速模型（2024-12），多模态能力强，适合批量素材分类与标签生成。',
    features: ['高速', '低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 轻量高速模型（2024-12），适合大批量低延迟任务。',
    features: ['超高速', '最低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3.0 Flash (Preview)',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google 3.0 预览版（2026），最新实验版本，适合尝鲜与测试。',
    features: ['最新预览', '多模态', '超长上下文'],
    tokenLimit: 2000000,
    contextWindow: 2000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Preview (free)' },
  },
  // ========== DeepSeek（官方：deepseek-v4-flash / deepseek-v4-pro 为最新主力）==========
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek-V4-Pro',
    provider: 'deepseek',
    category: ['text', 'code'],
    description: 'DeepSeek 最新旗舰推理模型（2026），擅长复杂推断，适合镜头到文案的对齐评分与优先级排序。2.5 折优惠中。',
    features: ['高智能推理', '判别', '重排序'],
    tokenLimit: 64000,
    contextWindow: 64000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.deepseek.com' },
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek-V4-Flash',
    provider: 'deepseek',
    category: ['text', 'code'],
    description: 'DeepSeek 最新高速模型（2026），高性价比，适合批量脚本生成与改写。（注：原 deepseek-chat / deepseek-reasoner 将废弃，统一迁移至此）',
    features: ['高性价比', '中文可用', '重写能力'],
    tokenLimit: 64000,
    contextWindow: 64000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.deepseek.com' },
  },
  // ========== 阿里云 Qwen ==========
  {
    id: 'qwen3.6-max-preview',
    name: 'Qwen3.6 Max (Preview)',
    provider: 'alibaba',
    category: ['text', 'code', 'image'],
    description: '阿里云通义千问最高智能预览版（2026-04），适合高质量解说稿与复杂文案创作。',
    features: ['最高智能', '中文专家', '复杂推理'],
    tokenLimit: 131072,
    contextWindow: 131072,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see dashscope.aliyun.com' },
  },
  {
    id: 'qwen3.6-plus',
    name: 'Qwen3.6 Plus',
    provider: 'alibaba',
    category: ['text', 'code', 'image'],
    description: '阿里云通义千问旗舰模型（2026-04），中文能力突出，适合中文解说文案生成与改写。',
    features: ['中文优化', '多模态', '成本可控'],
    tokenLimit: 131072,
    contextWindow: 131072,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see dashscope.aliyun.com' },
  },
  {
    id: 'qwen3.6-flash',
    name: 'Qwen3.6 Flash',
    provider: 'alibaba',
    category: ['text', 'code', 'image'],
    description: '阿里云通义千问高速模型（2026-04），响应快，适合批量分析与低延迟任务。',
    features: ['高速', '低成本', '中文优化'],
    tokenLimit: 131072,
    contextWindow: 131072,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see dashscope.aliyun.com' },
  },
  // ========== Moonshot / Kimi ==========
  {
    id: 'kimi-k2.6',
    name: 'Kimi K2.6',
    provider: 'moonshot',
    category: ['text', 'code', 'image'],
    description: '月之暗面最新旗舰（2026），原生多模态，Agent 性能出色，适合高质量解说稿生成。',
    features: ['原生多模态', '中文专家', '长上下文'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.moonshot.cn' },
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    provider: 'moonshot',
    category: ['text', 'code', 'image'],
    description: '月之暗面旗舰（2025），原生多模态，适合高质量解说稿生成与素材分析。',
    features: ['原生多模态', '中文专家', '长上下文'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.moonshot.cn' },
  },
  {
    id: 'kimi-k2',
    name: 'Kimi K2',
    provider: 'moonshot',
    category: ['text', 'code'],
    description: '月之暗面主力模型（2025），32K 上下文，适合中等长度解说稿一气生成。',
    features: ['长上下文', '中文专家', '快速'],
    tokenLimit: 32000,
    contextWindow: 32000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.moonshot.cn' },
  },
  {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    provider: 'moonshot',
    category: ['text', 'code'],
    description: '月之暗面推理增强版（2026），深度思考能力，适合复杂规划与逻辑推理任务。',
    features: ['推理增强', '深度思考', '中文专家'],
    tokenLimit: 32000,
    contextWindow: 32000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.moonshot.cn' },
  },
  // ========== 智谱 AI (Zhipu) ==========
  {
    id: 'glm-5',
    name: 'GLM-5',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 AI 最新旗舰模型（2026），中文能力强，适合中文视频解说与素材分析。',
    features: ['中文优化', '多模态', 'Agentic'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see open.bigmodel.cn' },
  },
  {
    id: 'glm-5-turbo',
    name: 'GLM-5 Turbo',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 AI 高速版（2026），响应快，适合批量分析与低延迟任务。',
    features: ['高速', '低成本', '中文优化'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see open.bigmodel.cn' },
  },
  {
    id: 'glm-5.1',
    name: 'GLM-5.1',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 AI 最新小版本（2026），能力微调，适合高效内容创作与分析。',
    features: ['高效', '中文优化', '多模态'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see open.bigmodel.cn' },
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 AI 高性能版本（2025），中文能力强，适合中文视频解说与素材分析。',
    features: ['中文优化', '多模态', '高性能'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see open.bigmodel.cn' },
  },
  {
    id: 'glm-4.6',
    name: 'GLM-4.6',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 AI 高性能版本（2025），适合内容分析与文案创作。',
    features: ['中文优化', '多模态', '高性能'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see open.bigmodel.cn' },
  },
  {
    id: 'glm-4',
    name: 'GLM-4',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 AI 旗舰模型（2024-01），中文能力强，适合中文视频解说与素材分析。',
    features: ['中文优化', '多模态', 'Agentic'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 0.1, output: 0.1, unit: '元/千tokens' },
  },
  // ========== 科大讯飞 (iFlytek) ==========
  {
    id: 'spark-4.0',
    name: 'Spark 4.0',
    provider: 'iflytek',
    category: ['text', 'audio'],
    description: '讯飞星火 4.0（2024-06），语音合成生态完整，适合与 TTS 联动生成配音解说。',
    features: ['语音生态', 'TTS 联动', '中文语音'],
    tokenLimit: 8192,
    contextWindow: 32000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see iflytek pricing' },
  },
  {
    id: 'spark-3.5',
    name: 'Spark 3.5',
    provider: 'iflytek',
    category: ['text', 'audio'],
    description: '讯飞星火 3.5（2024-01），语音识别与合成双能力，适合讯飞系 AI 配音工作流。',
    features: ['语音双能力', '中文', '生态完整'],
    tokenLimit: 8192,
    contextWindow: 32000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see iflytek pricing' },
  },
];

// =============================================================================
// 推荐配置（按任务类型）
// =============================================================================

export const MODEL_RECOMMENDATIONS: Record<string, string[]> = {
  script:   ['gpt-5.5', 'claude-opus-4.7', 'qwen3.6-plus', 'deepseek-v4-flash', 'kimi-k2.6'],
  analysis: ['gpt-5.5', 'claude-opus-4.7', 'gemini-2.5-pro', 'qwen3.6-max-preview'],
  code:     ['o3', 'claude-sonnet-4.6', 'deepseek-v4-pro', 'deepseek-v4-flash'],
  fast:     ['qwen3.6-flash', 'gpt-5.4-mini', 'glm-5-turbo', 'deepseek-v4-flash'],
};

// =============================================================================
// 模型查找纯函数
// =============================================================================

/** 根据 ID 精确查找模型 */
export const getModelById = (id: string): AIModel | undefined => {
  return AI_MODELS.find((model) => model.id === id);
};

/** 按提供者筛选模型列表 */
export const getModelsByProvider = (provider: ModelProvider): AIModel[] => {
  return AI_MODELS.filter((model) => model.provider === provider);
};

/** 按能力类别筛选模型 */
export const getModelsByCategory = (category: ModelCategory): AIModel[] => {
  return AI_MODELS.filter((model) => (model.category ?? ['general']).includes(category));
};

/** 获取指定任务类型的推荐模型列表 */
export const getRecommendedModels = (task: keyof typeof MODEL_RECOMMENDATIONS): AIModel[] => {
  const modelIds = MODEL_RECOMMENDATIONS[task] || [];
  return modelIds.map((id) => getModelById(id)).filter(Boolean) as AIModel[];
};
