/**
 * 字幕服务
 * 提供字幕生成、提取、翻译和渲染能力
 */

import { logger } from '@/utils/logger';
import type { SubtitleEntry } from '@/core/types';

// ============================================
// 类型定义
// ============================================

export interface SubtitleStyle {
  fontFamily: string;
  fontSize: number;
  color: string;
  backgroundColor: string;
  outline: boolean;
  outlineColor: string;
  position: 'top' | 'bottom' | 'center';
  alignment: 'left' | 'center' | 'right';
  opacity: number;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  entries: SubtitleEntry[];
  style?: SubtitleStyle;
}

export interface SubtitleExtractOptions {
  language?: string;
  maxDuration?: number;
}

export interface SubtitleTranslateOptions {
  targetLanguage: string;
  apiKey?: string;
  provider?: 'google' | 'deepl' | 'youdao';
}

const DEFAULT_SUBTITLE_STYLE: SubtitleStyle = {
  fontFamily: 'Arial, sans-serif',
  fontSize: 24,
  color: '#FFFFFF',
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  outline: true,
  outlineColor: '#000000',
  position: 'bottom',
  alignment: 'center',
  opacity: 1,
};

// ============================================
// 字幕服务
// ============================================

class SubtitleService {
  /**
   * 从视频中提取字幕（OCR + ASR）
   * @param videoPath 视频路径
   * @param options 提取选项
   */
  async extractSubtitles(
    videoPath: string,
    options?: SubtitleExtractOptions
  ): Promise<SubtitleTrack> {
    const { language = 'zh-CN', maxDuration } = options || {};

    logger.info('[SubtitleService] 提取字幕:', { videoPath, language });

    // TODO: 接入 OCR 服务提取文字 + ASR 服务提取语音
    // 目前返回空字幕
    const entries: SubtitleEntry[] = [];

    return {
      id: crypto.randomUUID(),
      language,
      entries,
      style: DEFAULT_SUBTITLE_STYLE,
    };
  }

  /**
   * 生成字幕文件（SRT / VTT / ASS）
   * @param track 字幕轨道
   * @param format 格式
   */
  async generateSubtitleFile(
    track: SubtitleTrack,
    format: 'srt' | 'vtt' | 'ass'
  ): Promise<string> {
    logger.info('[SubtitleService] 生成字幕文件:', {
      trackId: track.id,
      format,
      entries: track.entries.length,
    });

    switch (format) {
      case 'srt':
        return this.toSRT(track);
      case 'vtt':
        return this.toVTT(track);
      case 'ass':
        return this.toASS(track);
      default:
        throw new Error(`不支持的格式: ${format}`);
    }
  }

  /**
   * 翻译字幕
   * @param track 字幕轨道
   * @param options 翻译选项
   */
  async translateSubtitles(
    track: SubtitleTrack,
    options: SubtitleTranslateOptions
  ): Promise<SubtitleTrack> {
    const { targetLanguage, apiKey, provider = 'google' } = options;

    logger.info('[SubtitleService] 翻译字幕:', {
      sourceLang: track.language,
      targetLang: targetLanguage,
      provider,
    });

    // TODO: 接入翻译 API（Google / DeepL / 有道）
    // 目前返回原字幕
    return {
      ...track,
      id: crypto.randomUUID(),
      language: targetLanguage,
    };
  }

  /**
   * 烧录字幕到视频
   * @param videoPath 视频路径
   * @param subtitlePath 字幕文件路径
   * @param outputPath 输出路径
   * @param style 字幕样式
   */
  async burnSubtitles(
    videoPath: string,
    subtitlePath: string,
    outputPath: string,
    style?: Partial<SubtitleStyle>
  ): Promise<string> {
    const mergedStyle = { ...DEFAULT_SUBTITLE_STYLE, ...style };

    logger.info('[SubtitleService] 烧录字幕:', {
      video: videoPath,
      subtitle: subtitlePath,
      output: outputPath,
    });

    // TODO: 通过 Tauri 后端调用 FFmpeg 烧录字幕
    return outputPath;
  }

  /**
   * 转为 SRT 格式
   */
  private toSRT(track: SubtitleTrack): string {
    return track.entries
      .map((entry, index) => {
        const start = this.formatSRTTime(entry.startTime);
        const end = this.formatSRTTime(entry.endTime);
        return `${index + 1}\n${start} --> ${end}\n${entry.text}`;
      })
      .join('\n\n');
  }

  /**
   * 转为 VTT 格式
   */
  private toVTT(track: SubtitleTrack): string {
    const header = 'WEBVTT\n\n';
    const body = track.entries
      .map((entry) => {
        const start = this.formatVTTTime(entry.startTime);
        const end = this.formatVTTTime(entry.endTime);
        return `${start} --> ${end}\n${entry.text}`;
      })
      .join('\n\n');
    return header + body;
  }

  /**
   * 转为 ASS 格式（Advanced SubStation Alpha）
   */
  private toASS(track: SubtitleTrack): string {
    const header = `[Script Info]
Title: Generated by StoryForge
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

    const body = track.entries
      .map((entry) => {
        const start = this.formatASSTime(entry.startTime);
        const end = this.formatASSTime(entry.endTime);
        const text = entry.text.replace(/\n/g, '\\N');
        return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`;
      })
      .join('\n');

    return header + body;
  }

  private formatSRTTime(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 1000);
    return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')},${ms.toString().padStart(3, '0')}`;
  }

  private formatVTTTime(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 1000);
    return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${ms.toString().padStart(3, '0')}`;
  }

  private formatASSTime(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const cs = Math.floor((seconds % 1) * 100);
    return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${cs.toString().padStart(2, '0')}`;
  }
}

export const subtitleService = new SubtitleService();
export default subtitleService;
