/**
 * Anthropic 模型目录（10 个）
 *
 * Stage 8 PR-3.1：从 catalog.ts 拆分而来。
 */
import type { AIModel } from '@/types';

export const anthropicModels: AIModel[] = [
  {
    id: 'claude-sonnet-4.6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2026），长文本组织能力强，适合解说长稿编写与风格润色。',
    features: ['长文处理', '稳定风格', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2026），长文本能力强，适合解说长稿编写与风格润色。',
    features: ['长文处理', '稳定风格', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 主力模型（2026），综合能力均衡，适合各类文本与代码任务。',
    features: ['均衡', '长文处理', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4.7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 最高智能版本（2026），最高智能水平，适合复杂视频语义分析与高质量脚本创作。',
    features: ['最高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4.6',
    name: 'Claude Opus 4.6',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 旗舰模型（2026），适合复杂视频语义分析与高质量脚本创作。',
    features: ['高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4.5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2026），适合复杂视频语义分析与高质量脚本创作。',
    features: ['高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-opus-4',
    name: 'Claude Opus 4',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 旗舰基础模型（2026），适合复杂内容分析与高质量脚本创作。',
    features: ['高智能', '复杂推理', '视频理解'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-haiku-4.5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    category: ['text', 'code'],
    description: 'Anthropic 轻量高速模型（2026），适合批量分析与低延迟任务。',
    features: ['高速', '低成本', '精准'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 高智能模型（2024-06），长文本组织能力强，适合解说长稿编写与风格润色。',
    features: ['长文处理', '稳定风格', '中文优化'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 3, output: 15, unit: '$/MTokens' },
  },
  {
    id: 'claude-3.7-sonnet',
    name: 'Claude 3.7 Sonnet',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic 最新 3.7 系列（2025），长上下文与编程能力全面提升，适合复杂代码与长文本任务。',
    features: ['长上下文', '编程能力', '高智能'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see anthropic.com/pricing' },
  },
];
