/**
 * Google Gemini 模型目录（9 个）
 *
 * Stage 8 PR-3.1：从 catalog.ts 拆分而来。
 */
import type { AIModel } from '@/types';

export const googleModels: AIModel[] = [
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google 最新旗舰模型（2026-02），推理能力 2x+ 提升，1M token 上下文，适合超长视频素材理解与多镜头关联分析。',
    features: ['超长上下文', '多模态推理', '视频理解', 'Deep Think模式'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see ai.google.dev/pricing' },
  },
  {
    id: 'gemini-3.1-flash',
    name: 'Gemini 3.1 Flash',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 高性价比模型（2026-03），多模态能力强，适合批量素材分类与标签生成。',
    features: ['高速', '低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 最快最便宜模型（2026-03），适合大批量素材分类与低延迟任务。',
    features: ['高性价比', '快速', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google 旗舰模型（2025），超长上下文，适合长视频素材理解与多镜头关联分析。',
    features: ['超长上下文', '多模态推理', '视频理解'],
    tokenLimit: 2000000,
    contextWindow: 2000000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see ai.google.dev/pricing' },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 高速高性价比模型（2025），多模态能力强，适合批量素材分类与标签生成。',
    features: ['高速', '低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 轻量高性价比模型（2025），适合大批量素材分类与低延迟任务。',
    features: ['高性价比', '快速', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 高速模型（2024-12），多模态能力强，适合批量素材分类与标签生成。',
    features: ['高速', '低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'google',
    category: ['text', 'image', 'video'],
    description: 'Google 轻量高速模型（2024-12），适合大批量低延迟任务。',
    features: ['超高速', '最低成本', '多模态'],
    tokenLimit: 1000000,
    contextWindow: 1000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Free (with quota)' },
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3.0 Flash (Preview)',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google 3.0 预览版（2026），最新实验版本，适合尝鲜与测试。',
    features: ['最新预览', '多模态', '超长上下文'],
    tokenLimit: 2000000,
    contextWindow: 2000000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'Preview (free)' },
  },
];
