/**
 * OpenAI 模型目录（14 个）
 *
 * Stage 8 PR-3.1：从 catalog.ts 拆分而来。每个 provider 一个文件，便于独立维护。
 */
import type { AIModel } from '@/types';

export const openaiModels: AIModel[] = [
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 最新旗舰模型（2026），支持多模态输入，适合视频素材分析与解说文案生成。',
    features: ['多模态', '最高智能', '视频理解'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.5-pro',
    name: 'GPT-5.5 Pro',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 最新旗舰 Pro 模型（2026），最高智能水平，适合复杂视频语义分析与高质量解说稿创作。',
    features: ['最高智能', '视频理解', '复杂推理'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性能模型（2026），适合高质量脚本生成与改写。',
    features: ['高性能', '多模态', '编程能力'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性价比模型（2026），响应快、成本低，适合批量剪辑脚本生成与改写。',
    features: ['高性价比', '快速响应', '多模态'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.3-codex',
    name: 'GPT-5.3 Codex',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 代码专用模型（2026），编程能力强，适合代码分析与剪辑逻辑生成。',
    features: ['代码专家', '编程能力', '高智能'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.2',
    name: 'GPT-5.2',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 主力旗舰模型（2026），多模态能力均衡，适合综合视频分析与内容创作。',
    features: ['多模态', '高智能', '均衡全面'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.1',
    name: 'GPT-5.1',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 中高端模型（2026），适合内容分析与高质量文案生成。',
    features: ['多模态', '内容理解', '文案创作'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 基础旗舰模型（2026），支持视频理解，适合复杂视频语义分析。',
    features: ['多模态', '视频理解', '最高智能'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 轻量旗舰（2026），高性价比，适合批量脚本生成与改写。',
    features: ['高性价比', '多模态', '快速'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 旗舰多模态模型（2024-05），支持文本/代码/图像/视频理解，适合视频素材分析与解说文案生成。',
    features: ['多模态', '高智能', '视频理解'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: true,
    pricing: { input: 2.5, output: 10, unit: '$/MTokens' },
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性价比模型（2024-07），响应快、成本低，适合批量剪辑脚本生成与改写。',
    features: ['高性价比', '快速响应', '多模态'],
    tokenLimit: 128000,
    contextWindow: 128000,
    isPro: false,
    pricing: { input: 0.15, output: 0.6, unit: '$/MTokens' },
  },
  {
    id: 'o3',
    name: 'OpenAI o3',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 推理模型（2024-12），擅长复杂推断与规划，适合镜头匹配、时间轴修正等复杂决策。',
    features: ['高级推理', '复杂规划', '可靠判别'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'o3-mini',
    name: 'OpenAI o3-mini',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 轻量推理模型（2025-01），低成本推理，适合批量脚本评分与镜头优先级排序。',
    features: ['低成本推理', '快速', '编程能力'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 1.1, output: 4.4, unit: '$/MTokens' },
  },
  {
    id: 'o3-pro',
    name: 'OpenAI o3 Pro',
    provider: 'openai',
    category: ['text', 'code'],
    description: 'OpenAI 高端推理模型（2026），最强推理能力，适合最复杂的决策与规划任务。',
    features: ['最强推理', '复杂规划', '高端判别'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
];
